### ISSUE TITLE
PreparedTx.commit 报错

### ISSUE THREAD

**Issue by zhw1** [blockchain-jd-com/jdchain-starter#1]
到提交这步时报错：
com.jd.blockchain.utils.http.HttpStatusException: [status=404] null

	at com.jd.blockchain.utils.http.agent.HttpServiceAgent.processAndThrowHttpException(HttpServiceAgent.java:663)
	at com.jd.blockchain.utils.http.agent.HttpServiceAgent.invoke(HttpServiceAgent.java:582)
	at com.jd.blockchain.utils.http.agent.HttpServiceAgent.access$000(HttpServiceAgent.java:65)
	at com.jd.blockchain.utils.http.agent.HttpServiceAgent$ServiceInvocationHandler.invoke(HttpServiceAgent.java:934)
	at com.sun.proxy.$Proxy15.process(Unknown Source)
	at com.jd.blockchain.ledger.data.PreparedTx.commit(PreparedTx.java:60)
	at com.jd.blockchain.ledger.IntegrationTest.registerDataAccount(IntegrationTest.java:78)
	at com.jd.blockchain.ledger.IntegrationTest.register_dataAccount_more(IntegrationTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)

**Comment by zhaoGuangwei** [comment]
您好！
1.首先您要确保JDChain链已经搭建好，通过访问：http://ip:port能访问到网关，样例：http://192.168.151.39:8081；
2.验证peer节点能正常访问，格式：http://ip:port/ledgers，样例：http://192.168.151.39:7080/ledgers;
3.保证配置文件sys-contract.properties配置的参数信息都准确。具体参考doc文件夹中的相关文档。

祝愉快！
